//! 业务服务层

pub mod account;
pub mod announcement;
pub mod announcement_test;
pub mod api_key;
pub mod api_key_test;
pub mod audit;
pub mod backup;
pub mod billing;
pub mod billing_test;
pub mod concurrency;
pub mod credential;
pub mod email;
pub mod model_router;
pub mod oauth;
pub mod password_reset;
pub mod password_reset_test;
pub mod permission;
pub mod rate_limit;
pub mod redemption;
pub mod redemption_test;
pub mod scheduler;
pub mod scheduler_test;
pub mod subscription;
pub mod subscription_test;
pub mod totp;
#[cfg(test)]
mod totp_test;
pub mod user;
pub mod user_ext;
pub mod user_group;
pub mod user_test;

pub use account::AccountService;
pub use announcement::AnnouncementService;
pub use api_key::ApiKeyService;
pub use audit::{AsyncAuditLogger, AuditEntry, AuditFilter, AuditService};
pub use backup::BackupService;
pub use billing::BillingService;
pub use concurrency::{ConcurrencyConfig, ConcurrencyController};
pub use credential::CredentialService;
pub use email::{EmailConfig, EmailSender, MockEmailSender, SmtpEmailSender};
pub use model_router::ModelRouter;
pub use oauth::OAuthService;
pub use password_reset::PasswordResetService;
pub use permission::{Permission, PermissionConfig, PermissionGroup, PermissionService, Role};
pub use rate_limit::{DistributedRateLimiter, RateLimitConfig, RedisRateLimiter};
pub use redemption::RedemptionService;
pub use scheduler::SchedulerService;
pub use subscription::SubscriptionService;
pub use totp::TotpService;
pub use user::{LoginResponse, TotpSetupResponse, TotpStatus, UserService};
pub use user_group::UserGroupService;
